name: 'Terraform Actions CI/CD'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Main
      uses: actions/checkout@v4

    - name: Get Token GH App
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v3  
      with:
        application_id: ${{ secrets.GH_APPLICATION_ID }}     # create a secret in actions
        application_private_key: ${{ secrets.GH_APPLICATION_KEY }}

    - name: Extend Git credentials
      uses: de-vri-es/setup-git-credentials@v2.0.10
      with:
        credentials: https://user:${{ steps.get_workflow_token.outputs.token }}@github.com


    - name: Configure AWS Credentials
      id: aws_auth
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::739153323366:role/Role
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.4"


    - name: Terraform Init
      run: terraform -chdir=./terraform/env/${{ inputs.environment }} init

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: |
        terraform -chdir=./terraform/env/${{ inputs.environment }} plan -no-color > plan_output.txt
        echo "TERRAFORM_PLAN<<EOF" >> $GITHUB_ENV
        cat plan_output.txt >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const output = process.env.TERRAFORM_PLAN;
          const prNumber = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          github.rest.issues.createComment({
            issue_number: prNumber,
            owner: owner,
            repo: repo,
            body: `#### Terraform Plan Output for ${{ inputs.environment }}\n\`\`\`\n${output}\n\`\`\``
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform -chdir=./terraform/env/${{ inputs.environment }} apply -auto-approve -input=false
